#!/bin/bash
export SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export REPO_ROOT="${SCRIPT_DIR%/*}"

# Run memory tests
echo -n "memory/tb_memory_spram.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/memory/tb_memory_spram.v $REPO_ROOT/memory/memory_spram.v

echo -n "memory/tb_dff.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/memory/tb_dff.v $REPO_ROOT/memory/dff.v $REPO_ROOT/math/add.v $REPO_ROOT/logic/gates.v

echo -n "memory/tb_memory_dff.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/memory/tb_memory_dff.v $REPO_ROOT/memory/memory_dff.v $REPO_ROOT/memory/dff.v $REPO_ROOT/math/add.v $REPO_ROOT/logic/gates.v

# Run ALU tests
echo -n "math/tb_alu.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/math/tb_alu.v $REPO_ROOT/math/alu.v $REPO_ROOT/math/add.v $REPO_ROOT/logic/gates.v

# Run gate tests
echo -n "logic/tb.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/logic/tb.v $REPO_ROOT/logic/gates.v

# Run math tests
echo -n "math/tb.v -- "
$SCRIPT_DIR/runtest.sh $REPO_ROOT/math/tb.v $REPO_ROOT/math/add.v $REPO_ROOT/logic/gates.v

# Test assembler

# This test could be stronger, but for now, just 
# take a program I wrote myself in hack assembly
# and make sure the assembler's output agrees
# with the output generated by the NAND2Tetris
# web IDE: https://nand2tetris.github.io/web-ide/asm
#
# The book materials include a much longer
# program, pong. I verified that my assembler
# gives the same output as the web IDE for
# that case, but I don't want to include that
# code in this repo, because I don't think I
# have permission to include it under this
# repo's license.

# Make a temporary directory
TEMP_DIR=$(mktemp -d)

# Run the assembler (assumes uv is installed)
# and that a venv is in the repo root.
# Modify this to point to however you installed
# python.
echo -n "assembler/assembler.py -- "
uv run $REPO_ROOT/assembler/assembler.py $REPO_ROOT/assembler/add.asm > $TEMP_DIR/add.hack
if diff -B -q $TEMP_DIR/add.hack $REPO_ROOT/assembler/add.hack; then
  echo "OK"
else
  echo "FAIL"
  echo "Diff of object code assembled from assembler/add.asm :"
  echo " "
  diff $TEMP_DIR/add.hack $REPO_ROOT/assembler/add.hack
fi

# Now test packing the file up into binary
# Pack to binary, then use xxd, cut, sed to recover the original from the bytes
echo -n "assembler/object_code_ascii_to_big_endian.py -- "
uv run $REPO_ROOT/assembler/object_code_ascii_to_big_endian.py $TEMP_DIR/add.hack $TEMP_DIR/add.bin
xxd -b -c 2 $TEMP_DIR/add.bin | cut -d " " -f 2,3 | sed "s/ //" > $TEMP_DIR/add.bin.ascii
if diff -B -q $TEMP_DIR/add.bin.ascii $REPO_ROOT/assembler/add.hack; then
  echo "OK"
else
  echo "FAIL"
  echo "Diff of binary packed object code from assembler/add.asm :"
  echo " "
  diff $TEMP_DIR/add.bin.ascii $REPO_ROOT/assembler/add.hack
fi

# Clean up
rm -rf $TEMP_DIR

